Beginning.create(phrase: "I was late", category: "late")
Beginning.create(phrase: "Sorry I didn't show", category: "absent")
Beginning.create(phrase: "I dont have it", category: "dont_have_it")
Beginning.create(phrase: "I dont want to", category: "dont_want_to")
Beginning.create(phrase: "I wasn't very punctual", category: "late")
Beginning.create(phrase: "I guess I didn't appear", category: "absent")
Beginning.create(phrase: "I didn't bring what you wanted", category: "dont_have_it")
Beginning.create(phrase: "It doesn't seem appealing", category: "dont_want_to")
Beginning.create(phrase: "I'm late", category: "late")
Beginning.create(phrase: "I was absent", category: "absent")
Beginning.create(phrase: "I don't have it", category: "dont_have_it")
Beginning.create(phrase: "I don't want to", category: "dont_want_to")

Middle.create(phrase: "there was a jewish barista workshop")
Middle.create(phrase: "the scientific research papers were stolen")
Middle.create(phrase: "the brain surgery I had earlier was botched")
Middle.create(phrase: "I was at the library and lost track of time")
Middle.create(phrase: "the scientific research papers were stolen")
Middle.create(phrase: "I choked on my bubble tea")
Middle.create(phrase: "I dropped a bag of noodles")
Middle.create(phrase: "I lost my hair piece")
Middle.create(phrase: "my pizza ran away")


Final.create(phrase: "I spent too much time tripping on my shoes.")
Final.create(phrase: "I used my axe guitar.")
Final.create(phrase: "I punched it.")
Final.create(phrase: "I retaliated")
Final.create(phrase: "I puked.")
Final.create(phrase: "I died.")
Final.create(phrase: "I cried.")  
Final.create(phrase: "I ate a waffle.")
Final.create(phrase: "my doctor licked my face.")
Final.create(phrase: "I kicked a dog.")
Final.create(phrase: "I rubbed hot sauce all over my body.")